# Generated by Django 5.0.1 on 2024-01-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Auteur', 'verbose_name_plural': 'Auteurs'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mangalib.author', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Titre'),
        ),
    ]
